# Generated by Django 4.2.11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='用户名')),
                ('face_image', models.TextField(verbose_name='人脸图片(Base64)')),
                ('face_encoding', models.JSONField(verbose_name='人脸特征向量')),
                ('avatar_url', models.TextField(blank=True, verbose_name='头像URL')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='预设名称')),
                ('face_image', models.TextField(verbose_name='人脸图片(Base64)')),
                ('gesture_image', models.TextField(verbose_name='手势图片(Base64)')),
                ('gesture_encoding', models.JSONField(verbose_name='手势特征')),
                ('device_states', models.JSONField(verbose_name='设备状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='smartroom.user', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '预设',
                'verbose_name_plural': '预设',
                'db_table': 'presets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='preset',
            unique_together={('user', 'name')},
        ),
    ]
