# Generated by Django 4.2.11 on 2026-01-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='gesture_digit',
            field=models.IntegerField(blank=True, null=True, verbose_name='手势数字(0-5)'),
        ),
    ]
